matrix:
  include:
  - language: node_js
    node_js: 14
    script:
    - travis_wait 30 yarn && yarn lint && yarn test
    - cd react-native-in-app-payments-quickstart && yarn && yarn lint && cd ..
  - language: android
    sudo: false
    jdk: oraclejdk8
    os:
    - linux
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.yarn-cache"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    android:
      components:
      - tools
      - platform-tools
      - tools
      - yes | sdkmanager "platforms;android-30"
      - yes | sdkmanager "build-tools;30.0.2"
      # - build-tools-30.0.2
      # - android-29
      - extra-google-google_play_services
    install:
    - nvm install 14
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - cd react-native-in-app-payments-quickstart
    - yarn
    script:
    - cd android
    - "./gradlew clean build"
  - language: objective-c
    os: osx
    osx_image: xcode11.2
    node_js: 14
    cache:
      directories:
      - "$HOME/.yarn-cache"
    before_install:
    - gem install cocoapods
    - nvm install 14
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - cd react-native-in-app-payments-quickstart
    - yarn
    - cd ios
    script:
    - travis_wait 30 xcodebuild -workspace RNInAppPaymentsQuickstart.xcworkspace -configuration Debug
      -scheme RNInAppPaymentsQuickstart -destination "platform=iOS Simulator,OS=12.2,name=iPhone
      X" -derivedDataPath build/RNInAppPaymentsQuickstart
notifications:
  slack:
    secure: xwbDusxnj1eSu4lLXqX7E6+JoE+V651d3xKa+KJKjcsyNftDnTIInTh480nM2Busev8GKcLol93kBMnJYb3mQuz5hv90lX8DCB54eAnShG8F1MhW3ap1E7guC0nt2G75GR/g0v2jKiFwYLLER3dDvqkTCBkHwGGDHpeMq9x7kh++ZlXzbifK/Ok8IH+kLHBp6cGocjx8CFp2Tg+ZBNFY6sWzzBTt3fdEFgzZzc7VqJxzGR2vjyZd5MtqnB6emaaQ7d20EtBGxAo+ttnmIp46zeiPUHAlwxakaIJz1VGabrMz/k0oLyQw7d3YQ6MoJ6kNcS808d7cyrhR1h0ZZ42Uq21OCiNIBnbDBB8kjPuVOOm16CVTHv3rEkQzrmZ23S+LZRWDbw0/5VlOew9rZvNtcSeekcR37AShBbzS4X1Cs6nfGSfNe2Sx1KHbrEPQQ9utrBS1tjTQcIOlbE464rw7DqkVLJA/DSXEePtvpWnA3j2M0vFLLaZaA3CfuRaUZ4WW6reaG9GHdwJ7GW8X8NpeDH9Du0iNC3phCQ2n6xvf4eozDmwunaD1u3zeXLjoIcsfOFkFTZiwuPEANTBWEKdsxCqUn4q5nXlWPBJ/nvc46+v0ySvlWJ2Tu5cX1G2C/WszMjlGZFR0FbzGHiRDL/0jIzTiJRtVgnlJ5b6I5PPiHus=
    on_success: change
    template:
        - "@oncall"
        - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{duration}"
  email:
    recipients:
      - devs-apex-alerts+travis@squareup.com
    on_success: change
